---
# This file is copied from https://github.com/voxpupuli/modulesync_config
HOSTS:
  ubuntu-1404-x64:
    platform: ubuntu-14.04-amd64
    hypervisor: docker
    #image: ubuntu:14.04
    image: electrical/ubuntu:14.04
    docker_preserve_image: true
    docker_cmd: '["/sbin/init"]'
    docker_image_commands:
      - 'apt-get install -y net-tools wget apt-transport-https locales'
      - 'locale-gen en_US.UTF-8'
CONFIG:
  trace_limit: 200
  masterless: true
...
# vim: syntax=yaml
